version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    platform: linux/arm64/v8
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - action.auto_create_index=true
      - xpack.security.enabled=false  # 개발 환경에서는 보안 비활성화
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    build: ./logstash
    platform: linux/arm64/v8
    container_name: logstash
    ports:
      - "5001:5001"  # Logstash가 TCP 포트 5001에서 로그 수신
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    platform: linux/arm64/v8
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge